name: Deploy Springboot App
on:
    repository_dispatch:
      types: [deploy-springboot]


jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout app repo
        uses: actions/checkout@v4
        with:
          repository: mikechiloane/recceda-startup
          token: ${{ secrets.ACTIONS_REPO_PAT }}
          ref: main

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build and package
        run: mvn clean package --no-transfer-progress

      - name: Zip artifacts
        run: |
          mkdir bundle
          cp -r appspec.yml scripts/ target/*.jar bundle/
          cd bundle && zip -r ../deployment.zip .

      - name: Upload to S3
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --acl private
        env:
          AWS_S3_BUCKET: ${{ secrets.S3_BUCKET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
          SOURCE_DIR: "."
          DEST_DIR: "/"
          FILES: "deployment.zip"

      - name: Deploy with CodeDeploy
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          aws deploy create-deployment \
            --application-name ${{ secrets.CODEDEPLOY_APP }} \
            --deployment-group-name ${{ secrets.CODEDEPLOY_GROUP }} \
            --s3-location bucket=${{ secrets.S3_BUCKET }},key=deployment.zip,bundleType=zip \
            --region ${{ secrets.AWS_REGION }}